# Generated by Django 5.1 on 2024-08-31 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Cidade',
            new_name='cidade',
        ),
    ]
